rvm:
  - 2.2.3
language: ruby
notifications:
  irc:
    channels:
      - "irc.freenode.org#rvm-test"
      - "irc.freenode.org#rvm"
  email:
    recipients:
      - mpapis@gmail.com
      - healey.rich@gmail.com
    on_failure: change
