rvm:
  - "--install ."
language: ruby
notifications:
  irc:
    channels:
      - "irc.freenode.org#rvm-test"
      - "irc.freenode.org#rvm"
  email:
    recipients:
      - mpapis@gmail.com
      - healey.rich@gmail.com
    on_failure: change
  slack:
    secure: ymbDlD3DmDDBE5F+Yur4Zv8j5cVk1+DL7vtoedwuryOx919kftwVEytTjeZm6nCc4t1o4u8WNfhbN5nHBgK8g50u2rAl+NmKgPEpwsMu6T3ymKwGWqJAuUOze4iEHK/EyDRZ5XC407H2SBgkjfqeuSBVaBiISCheruntzZSzRCs=
    on_success: change
    on_failure: always
    on_pull_requests: false