rvm:
  - 2.0.0
language: ruby
notifications:
  irc:
    channels:
      - "irc.freenode.org#rvm-test"
      - "irc.freenode.org#rvm"
  email:
    recipients:
      - mpapis@gmail.com
      - envygeeks@gmail.com
    on_failure: change
